* Rezepte
** Kochen

*** Rotweinsoße mit grünen Nudeln
**** Zutaten für 2 Personen
- 1 Zwiebel
- 1 Knoblauchzehe
- 1 EL Öl
- 150g roher Schinken (eventuell roher/gekochter halb/halb)
- 2 EL Tomatenmark
- 125 ml Rotwein
- 2 EL Creme Fraiche
- Salz
- Pfeffer
- Paprikapulver

**** Zubereitung
Zwiebeln und Knoblauch sehr fein hacken und leicht andünsten, Schinken in feine Streifen schneiden und 5 min mitdünsten. Tomatenmark dazu rühren, würzen, mit Rotwein ablöschen. Creme Fraiche dazu und 5 min köcheln lassen.

*** braune Soße
**** Zutaten für 2 Personen:
- 100ml Rotwein
- 2 EL Worcestersauce
- 1 TL Tomy Senf mild
- 200 ml Gemüsebouillon (200ml Wasser + 1 gehäufter TL Pulver)
- 2 mittlere Schalotten
- 2 kleine Zehen Knoblauch
- 2 EL Creme Fraiche
- Salz
- Pfeffer
- Rosmarin
- Paprikapulver
- Basilikum
- 1 TL TK Kräuter Iglo feldfrische Mischung

**** Zubereitung:
Nach dem Braten von Fleisch in der selben Pfanne die Schalotten und den Knoblauch andünsten.
Dann Rotwein, Worcestersauce und Senf mischen und damit ablöschen. Gut einkochen lassen. Anschließend die Brühe zugeben, ebenfalls gut einkochen lassen. Die Creme Fraiche einrühren, würzen


*** Steffen Hensslers Spaghetti mit frischer Tomatensauce
**** Zutaten für 4 Personen:
- 250g Spaghetti
- Salz
- 1 Schalotte
- 1 Knolauchzehe
- 500g reife Flaschen- oder Kirschtomaten
- 1,5 EL Tomatenmark
- 1 kleine getrocknete Chilischote
- Pfeffer
- Zucker
- 3 EL Olivenöl
- 1 Büffelmozzarella (250g)
- 1 Handvoll Basilikumblätter

**** Zubereitung:
- Spaghetti nach Packungsanleitung bissfest garen
- inzwischen Schalotte und Knoblauch schälen. Den Stielansatz der Tomaten keilförmig herausschneiden. Tomaten, Schalotte und Knoblauch grob zerkleinern und in eine Schüssel geben. Tomatenmark und zerbröselte Chilischote ebenfalls in die Schüssel geben. Alles mit dem Stabmixer fein pürieren. Sauce durch ein feines Sieb streichen und mit Salz, Pfeffer und 1 Prise Zucker würzen. Olivenöl einrühren.
- Mozzarella abtropfen lassen und in Stücke zupfen. Nudeln abgießen, mit 50ml Kochwasser und der Sauce vermengen. Mit Basilikumblättern und Mozzarella bestreuen. Sofort servieren.

*** italienische Paprikacreme
**** Zutaten für 4 Personen:
- 3 rote Paprikaschoten
- 1 kleine Zwiebel
- 30g Margarine
- 2 EL Paprika Edelsüß
- 1 EL Tomatenmark
- 30g Instant-Haferflocken
- 125 ml Traubensaft
- 1l Gemüsebrühe
- 125g saure Sahne
- 1 Knoblauchzehe
- Pfeffer
- Salz
- Basilikumblätter

**** Zubereitung
Paprika waschen, entkernen und fein würfeln. Die Zwiebel kleinhacken und in Margarine anschwitzen. Einige Paprikawürfel zur Seite legen, die übrigen in die Pfanne geben und kurz mit garen. Paprikagewürz, Tomatenmark und Instant-Haferflocken hinzufügen und anrösten. Mit Traubensaft und Gemüsebrühe ablöschen und ca 20 min köcheln lassen.
Die Suppe pürieren und cremig einkochen lassen. Von der Herdplatte ziehen und den Großteil der sauren Sahne einrühren. Mit gepresstem Knoblauch, Pfeffer und Salz abschmecken. Die Paprikacreme mit einem Tupfer saurer Sahne, den Basilikumblättern und den Paprikawürfeln garniert servieren. 
zusätzlich Hackbällchen und Croutons 

*** Lachs mit Mandel-Bohnen
**** Zutaten für 4 Personen:
- 1 rote Paprikaschote
- 300g grüne Bohnen
- Salz
- Pfeffer
- 200g Couscous (Weizengrieß)
- 250ml Gemüsebrühe
- 3 Stiele Petersiie
- 10g Ingwer
- 400g Lachsfilet
- 2 TL Zitronensaft
- 1 EL Öl
- 1 EL flüssiger Honig
- 50g Mandelblättchen
- 1 EL Butter

**** Zubereitung:
Paprika in Streifen schneiden. Bohnen in Salzwasser ca 15 min kochen, abgießen. Couscous in eine Form geben. Brühe aufkochen, darübergeben. Couscous ca 10 min quellen lassen. Petersilie hacken, Ingwer reiben. Fisch mit Salz, Pfeffer und Zitronensaft würzen. Öl erhitzen. Lachs und Paprika darin 6-8 min braten. Honig, Ingwer und Petersilie zugeben. Die Mandeln in heißer Butter anrösten. Bohnen darin schwenken. 

*** Lachsfilet in Pistazienbutter
**** Zutaten für 4 Personen:
- 1 Bio-Zitrone
- 5 Stiele Petersilie
- 2 EL Pistazienkerne
- 200g Bandnudeln
- Salz
- Pfeffer
- 600g Lachsfilet (ohne Haut)
- 2 EL Mehl
- 2 EL Öl
- 40g + 1 EL Butter

**** Zubereitung:
Zitrone waschen, trocken tupfen. Hälfte der Schale abschälen, in feine Streifen schneiden. Petersilie waschen, Blättchen abzupfen, hacken. Pistazien hacken, mit Petersilie und Zitronenschale mischen. Nudeln in Salzwasser nach Packungsanleitung kochen. Lachs in 4 Stücke schneiden. Zitrone halbieren, Saft auspressen. Lachs mit 1-2 EL Zitronensaft, Salz und Pfeffer würzen. In Mehl wenden. Öl in eienr beschichteten Pfanne erhitzen. Fisch darin unter wenden ca 5 min braten. 40g Butter schmelzen, Pistazienmischung darin darin schwenken. Nudeln abgießen, 1 EL Butter, Rest Zitronensaft und -schale untermischen. Mit Salz und Pfeffer würzen. Lachs mit Pistazienbutter und Nudeln anrichten.

*** GR Grießbrei
500ml Milch/Brühe
70g Grieß
(20g Butter)

Zucker nach Belieben

** Backen

**** Zubereitung

*** GR Pfannkuchenteig
250g Mehl
500ml Milch
3 Eier

für Wraps: Salz, Pfeffer, Schnittlauch

*** Waffeln
250g Mehl
450ml Milch
2 Eigelb + Eischnee
(0,5 TL Salz)
50-100g Butter, geschmolzen
halbes Päckchen Backpulver

Mehl, Milch, Eigelb, Backpulver und Butter mischen und ganz zuletzt Eischnee unterheben. Zucker nach belieben.


** Kochideen
- Knoblauch-Rahmsoße
- Flusskrebse Petersilie+Dill mit Reis/Nudeln
- Knoblauchschnitzel mit Käsespätzle
- Spaghetti aglio oilo + pepperoni + garnelen
- hotdogs mit käse
- spaghetti bolognese
- lachs in sahnesoße
- knuspriges hähnchen aus dem ofen mit reis
- cheeseburger
- chevapcici
- lasagne
- pizza
- tortellini mit käsesoße
- tortellini mit schinken-sahne-soße
- bifteki
- burritos
- gemüsepfanne
- pfeffer-rahm-geschnetzeltes mit kroketten
- chili con carne
- gefüllte paprika
- lamm
- hackbällchen mit brauner soße m frühlingszwiebeln und karotte
- lachs toskana/provence
- fisch mit zitronen-dill-soße
- hähnchen/pute mit kräutersoße und bohnengemüse
- flusskrebe mit linguini & zitrone
